# Generated by Django 5.2.7 on 2026-07-25 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('org_admin', 'Org Admin'), ('property_manager', 'Property Manager'), ('approver', 'Approver'), ('viewer', 'Viewer')], default='viewer', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=32)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.organization')),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('fiscal_period', models.CharField(max_length=16)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_review', 'Manager Review'), ('finance_review', 'Finance Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=32)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.organization')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_projects', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.property')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_period', models.CharField(max_length=16)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_review', 'Manager Review'), ('finance_review', 'Finance Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=32)),
                ('at', models.DateTimeField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_events', to='core.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_events', to='core.project')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_events', to='core.property')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='entitled_users', to='core.property'),
        ),
        migrations.CreateModel(
            name='PropertyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_period', models.CharField(max_length=16)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('project_count', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('by_category', models.JSONField(default=dict)),
                ('by_status', models.JSONField(default=dict)),
                ('backlog_by_level', models.JSONField(default=dict)),
                ('cycle_time_sum_hours', models.FloatField(default=0.0)),
                ('cycle_time_n', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='core.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='core.property')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['org', 'property', 'fiscal_period'], name='core_projec_org_id_2a0f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['org', 'status'], name='core_projec_org_id_9b6c10_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['org', 'category'], name='core_projec_org_id_040811_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('property', 'fiscal_period'), name='uniq_budget_per_property_period'),
        ),
        migrations.AddIndex(
            model_name='approvalevent',
            index=models.Index(fields=['org', 'project'], name='core_approv_org_id_b4ed01_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyaggregate',
            constraint=models.UniqueConstraint(fields=('property', 'fiscal_period'), name='uniq_prop_agg'),
        ),
    ]
